/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/heroes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Heroes */
        get: operations["list_heroes_api_v1_heroes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/heroes/{hero_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Hero */
        get: operations["get_hero_api_v1_heroes__hero_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/heroes/{hero_id}/similar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Similar Heroes */
        get: operations["similar_heroes_api_v1_heroes__hero_id__similar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Items */
        get: operations["list_items_api_v1_items_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/counters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Counters
         * @description Full hero_counters table — used by the frontend to build the
         *     counter-pick heatmap client-side rather than computing it per-pair on
         *     the server, since the matrix is small (40 heroes) and static per patch.
         */
        get: operations["list_counters_api_v1_counters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/emblems": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Emblems */
        get: operations["list_emblems_api_v1_emblems_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/battle-spells": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Battle Spells */
        get: operations["list_battle_spells_api_v1_battle_spells_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Patches */
        get: operations["list_patches_api_v1_patches_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patches/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Current Patch */
        get: operations["get_current_patch_api_v1_patches_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/predict/win-probability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Predict Win Probability
         * @description Regular `def`, not `async def`: this endpoint is CPU-bound (pandas
         *     feature engineering + XGBoost inference + SHAP), not I/O-bound.
         *     FastAPI automatically runs sync route handlers in a thread pool, which
         *     is the correct behavior here — making this `async def` without an
         *     actual await inside would block the event loop instead of helping it.
         */
        post: operations["predict_win_probability_api_v1_predict_win_probability_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recommendations/hero-pick": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Recommend Hero Pick
         * @description Sync `def` — see win_prediction.py for why (CPU-bound, not I/O-bound).
         */
        post: operations["recommend_hero_pick_api_v1_recommendations_hero_pick_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recommendations/build": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Recommend Build
         * @description Sync `def` — see win_prediction.py for why (CPU-bound, not I/O-bound).
         */
        post: operations["recommend_build_api_v1_recommendations_build_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/refresh-ml-data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Ml Data Endpoint
         * @description The ML engines read from pre-extracted parquet snapshots
         *     (ml/data/raw/), not live Postgres — call this after editing
         *     heroes/items/builds/counters/synergies/patches in the database so
         *     the running server picks up the change without a restart.
         */
        post: operations["refresh_ml_data_endpoint_api_v1_admin_refresh_ml_data_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BattleSpellSummary */
        BattleSpellSummary: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Cooldown */
            cooldown: number;
        };
        /** BestPickEntry */
        BestPickEntry: {
            /** Hero Id */
            hero_id: number;
            /** Hero Name */
            hero_name: string;
            /** Composite Score */
            composite_score: number;
            /** Explanation */
            explanation: string;
            /** Win Prob Uplift */
            win_prob_uplift?: number | null;
            unified_explanation: components["schemas"]["ExplanationSchema"];
        };
        /** BuildRequest */
        BuildRequest: {
            /** Hero Id */
            hero_id: number;
            /**
             * Enemy Picks
             * @description Hero IDs already drafted by the enemy team.
             */
            enemy_picks?: number[];
            /** Patch Version */
            patch_version?: string | null;
        };
        /** BuildResponse */
        BuildResponse: {
            /** Hero Name */
            hero_name: string;
            /** Tier */
            tier: string;
            /** Items */
            items: string[];
            /** Emblem */
            emblem: string;
            /** Battle Spell */
            battle_spell: string;
            /** Explanation */
            explanation: string[];
            threat_profile: components["schemas"]["ThreatProfile"];
            /** Patch Version */
            patch_version: string;
            unified_explanation: components["schemas"]["ExplanationSchema"];
        };
        /**
         * ConfidenceLevel
         * @enum {string}
         */
        ConfidenceLevel: "high" | "medium" | "low";
        /** ConfidenceSchema */
        ConfidenceSchema: {
            level: components["schemas"]["ConfidenceLevel"];
            source: components["schemas"]["ConfidenceSource"];
            /**
             * Basis
             * @description Human-readable justification — always discloses data provenance caveats.
             */
            basis: string;
        };
        /**
         * ConfidenceSource
         * @enum {string}
         */
        ConfidenceSource: "curated_data" | "transferred_data" | "heuristic_default" | "model_inference";
        /** CounterPickEntry */
        CounterPickEntry: {
            /** Hero Id */
            hero_id: number;
            /** Hero Name */
            hero_name: string;
            /** Counter Score */
            counter_score: number;
            /** Countered Enemy Heroes */
            countered_enemy_heroes: string[];
            unified_explanation: components["schemas"]["ExplanationSchema"];
        };
        /**
         * Direction
         * @enum {string}
         */
        Direction: "positive" | "negative" | "neutral";
        /** EmblemSummary */
        EmblemSummary: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Type */
            type: string;
        };
        /** ExplanationFactorSchema */
        ExplanationFactorSchema: {
            /** Label */
            label: string;
            /** Description */
            description: string;
            /** Value */
            value?: number | null;
            /** @default neutral */
            direction: components["schemas"]["Direction"];
        };
        /** ExplanationSchema */
        ExplanationSchema: {
            /** Module */
            module: string;
            /** Summary */
            summary: string;
            /** Factors */
            factors?: components["schemas"]["ExplanationFactorSchema"][];
            confidence: components["schemas"]["ConfidenceSchema"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HeroCounterEntry */
        HeroCounterEntry: {
            /** Hero Id */
            hero_id: number;
            /** Countered By Id */
            countered_by_id: number;
            /** Counter Score */
            counter_score: number;
            /** Reason */
            reason: string | null;
            /** Patch Version */
            patch_version: string;
        };
        /** HeroDetail */
        HeroDetail: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Role */
            role: string;
            /** Secondary Role */
            secondary_role: string | null;
            /** Specialty */
            specialty: string;
            /** Damage Type */
            damage_type: string;
            /** Preferred Lane */
            preferred_lane: string;
            /** Difficulty */
            difficulty: number;
            /** Is Meta */
            is_meta: boolean;
            /** Is Op */
            is_op: boolean;
            /**
             * Stats
             * @default []
             */
            stats: components["schemas"]["HeroStatsSummary"][];
        };
        /** HeroPickMeta */
        HeroPickMeta: {
            /** Patch Version */
            patch_version: string;
            /** Candidates Considered */
            candidates_considered: number;
            /** Win Prob Uplift Used */
            win_prob_uplift_used: boolean;
        };
        /** HeroPickRequest */
        HeroPickRequest: {
            ally_picks: components["schemas"]["LanePicks"];
            enemy_picks: components["schemas"]["LanePicks"];
            /** Banned Heroes */
            banned_heroes?: number[];
            /**
             * Target Lane
             * @enum {string}
             */
            target_lane: "exp" | "gold" | "mid" | "jungle" | "roam";
            /** Patch Version */
            patch_version?: string | null;
            /** Rank Tier */
            rank_tier?: string | null;
            /**
             * Top K
             * @default 5
             */
            top_k: number;
        };
        /** HeroPickResponse */
        HeroPickResponse: {
            /** Best Picks */
            best_picks: components["schemas"]["BestPickEntry"][];
            /** Counter Picks */
            counter_picks: components["schemas"]["CounterPickEntry"][];
            /** Synergy Picks */
            synergy_picks: components["schemas"]["SynergyPickEntry"][];
            meta: components["schemas"]["HeroPickMeta"];
        };
        /** HeroStatsSummary */
        HeroStatsSummary: {
            /** Patch Version */
            patch_version: string;
            /** Win Rate */
            win_rate: number | null;
            /** Pick Rate */
            pick_rate: number | null;
            /** Ban Rate */
            ban_rate: number | null;
        };
        /** HeroSummary */
        HeroSummary: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Role */
            role: string;
            /** Secondary Role */
            secondary_role: string | null;
            /** Specialty */
            specialty: string;
            /** Damage Type */
            damage_type: string;
            /** Preferred Lane */
            preferred_lane: string;
            /** Difficulty */
            difficulty: number;
            /** Is Meta */
            is_meta: boolean;
            /** Is Op */
            is_op: boolean;
        };
        /** ItemSummary */
        ItemSummary: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Tier */
            tier: number;
            /** Cost */
            cost: number;
        };
        /**
         * LanePicks
         * @description Hero IDs by lane. Use null for an unfilled slot.
         */
        LanePicks: {
            /** Exp */
            exp?: number | null;
            /** Gold */
            gold?: number | null;
            /** Mid */
            mid?: number | null;
            /** Jungle */
            jungle?: number | null;
            /** Roam */
            roam?: number | null;
        };
        /** PatchSummary */
        PatchSummary: {
            /** Patch Version */
            patch_version: string;
            /**
             * Release Date
             * Format: date
             */
            release_date: string;
            /** Codename */
            codename: string | null;
            /** Is Current */
            is_current: boolean;
        };
        /** SimilarHeroEntry */
        SimilarHeroEntry: {
            /** Hero Id */
            hero_id: number;
            /** Hero Name */
            hero_name: string;
            /** Similarity */
            similarity: number;
        };
        /** SynergyPickEntry */
        SynergyPickEntry: {
            /** Hero Id */
            hero_id: number;
            /** Hero Name */
            hero_name: string;
            /** Synergy Score */
            synergy_score: number;
            /** Synergized Ally Heroes */
            synergized_ally_heroes: string[];
            unified_explanation: components["schemas"]["ExplanationSchema"];
        };
        /** ThreatProfile */
        ThreatProfile: {
            /** Physical Count */
            physical_count: number;
            /** Magic Count */
            magic_count: number;
            /** Tank Count */
            tank_count: number;
            /** Burst Threat Score */
            burst_threat_score: number;
            /** Cc Density */
            cc_density: number;
            /** Sustain Threat */
            sustain_threat: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WinPredictionRequest */
        WinPredictionRequest: {
            /** @description All 5 lanes must be filled — this predicts a complete draft. */
            ally_picks: components["schemas"]["LanePicks"];
            enemy_picks: components["schemas"]["LanePicks"];
            /** Ally Bans */
            ally_bans?: number[];
            /** Enemy Bans */
            enemy_bans?: number[];
            /**
             * Patch Version
             * @description Defaults to the current patch if omitted.
             */
            patch_version?: string | null;
            /**
             * Rank
             * @default Mythic
             */
            rank: string;
        };
        /** WinPredictionResponse */
        WinPredictionResponse: {
            /** Win Probability */
            win_probability: number;
            /** Patch Version */
            patch_version: string;
            explanation: components["schemas"]["ExplanationSchema"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_heroes_api_v1_heroes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HeroSummary"][];
                };
            };
        };
    };
    get_hero_api_v1_heroes__hero_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hero_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HeroDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    similar_heroes_api_v1_heroes__hero_id__similar_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                hero_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimilarHeroEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_items_api_v1_items_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemSummary"][];
                };
            };
        };
    };
    list_counters_api_v1_counters_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HeroCounterEntry"][];
                };
            };
        };
    };
    list_emblems_api_v1_emblems_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmblemSummary"][];
                };
            };
        };
    };
    list_battle_spells_api_v1_battle_spells_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BattleSpellSummary"][];
                };
            };
        };
    };
    list_patches_api_v1_patches_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatchSummary"][];
                };
            };
        };
    };
    get_current_patch_api_v1_patches_current_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatchSummary"];
                };
            };
        };
    };
    predict_win_probability_api_v1_predict_win_probability_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WinPredictionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WinPredictionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recommend_hero_pick_api_v1_recommendations_hero_pick_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HeroPickRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HeroPickResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recommend_build_api_v1_recommendations_build_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BuildRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuildResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_ml_data_endpoint_api_v1_admin_refresh_ml_data_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
